name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - test-build-and-push

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # no test is required
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: bash docker-build/build_cluster_docker.sh all

      - name: Log into dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          # strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ $VERSION == "test-build-and-push" ] && VERSION=latest
          bash docker-build/build_cluster_docker.sh push
